"""
Generate Rust reduce-bend GPKG test data from tests/reduce_bend_unittest.py.

This mirrors the simplify migration pattern:
- input GPKG per case
- expected-output GPKG per case (generated by Python reference algorithm)
- manifest JSON consumed by Rust integration tests

Usage (QGIS Python environment):
    python generate_test_reduce_bend_gpkg.py

Outputs:
    tests/bend/test_rb_XX_input.gpkg
    tests/bend/test_rb_XX_expected.gpkg
    tests/bend/test_manifest_reduce_bend.json
"""

import ast
import json
import os
import sys


# Standalone QGIS/conda bootstrap
QGIS_PREFIX_PATH = os.environ.get(
    "QGIS_PREFIX_PATH",
    r"C:\Users\xxx\miniconda3\envs\data",
)

if os.name == "nt":
    qgis_bin = os.path.join(QGIS_PREFIX_PATH, "Library", "bin")
    if os.path.isdir(qgis_bin):
        os.environ["PATH"] = qgis_bin + os.pathsep + os.environ.get("PATH", "")

from qgis.core import (  # pylint: disable=import-error
    QgsApplication,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransformContext,
    QgsFeature,
    QgsField,
    QgsFields,
    QgsGeometry,
    QgsLineString,
    QgsPoint,
    QgsPolygon,
    QgsProcessingFeedback,
    QgsVectorFileWriter,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QVariant  # pylint: disable=import-error


# Add repo root to path for algorithm imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

try:
    from core.reduce_bend import ReduceBend
except ImportError:
    from reduce_bend import ReduceBend


def create_point(coord):
    return QgsPoint(coord[0], coord[1])


def create_line_geom(coords):
    pts = [create_point(c) for c in coords]
    return QgsGeometry(QgsLineString(pts))


def create_polygon_geom(outer, inners=None):
    outer_ls = QgsLineString([create_point(c) for c in outer])
    pol = QgsPolygon()
    pol.setExteriorRing(outer_ls)
    if inners:
        for inner in inners:
            inner_ls = QgsLineString([create_point(c) for c in inner])
            pol.addInteriorRing(inner_ls)
    return QgsGeometry(pol)


def build_geom(spec):
    if spec["type"] == "line":
        return create_line_geom(spec["coords"])
    if spec["type"] == "polygon":
        return create_polygon_geom(spec["outer"], spec.get("inners", []))
    if spec["type"] == "point":
        return QgsGeometry(create_point(spec["coord"]))
    raise ValueError(f"Unknown type: {spec['type']}")


def make_features(geom_list):
    features = []
    for geom in geom_list:
        f = QgsFeature()
        f.setGeometry(geom)
        features.append(f)
    return features


def run_reduce_bend(geom_list, diameter, smooth_line, del_outer, del_inner):
    features = make_features(geom_list)
    feedback = QgsProcessingFeedback()
    results = ReduceBend.reduce(
        features,
        diameter,
        smooth_line,
        del_outer,
        del_inner,
        False,
        feedback,
    )
    return [f.geometry() for f in results.qgs_features_out]


def write_gpkg(filepath, geometries):
    if not geometries:
        fields = QgsFields()
        fields.append(QgsField("id", QVariant.Int))
        opts = QgsVectorFileWriter.SaveVectorOptions()
        opts.driverName = "GPKG"
        opts.fileEncoding = "UTF-8"
        writer = QgsVectorFileWriter.create(
            filepath,
            fields,
            QgsWkbTypes.LineString,
            QgsCoordinateReferenceSystem(),
            QgsCoordinateTransformContext(),
            opts,
        )
        del writer
        return

    geom_types = {g.wkbType() for g in geometries}
    if len(geom_types) == 1:
        geom_type = geometries[0].wkbType()
    else:
        geom_type = QgsWkbTypes.Unknown

    fields = QgsFields()
    fields.append(QgsField("id", QVariant.Int))
    fields.append(QgsField("diameter", QVariant.Double))

    opts = QgsVectorFileWriter.SaveVectorOptions()
    opts.driverName = "GPKG"
    opts.fileEncoding = "UTF-8"

    writer = QgsVectorFileWriter.create(
        filepath,
        fields,
        geom_type,
        QgsCoordinateReferenceSystem(),
        QgsCoordinateTransformContext(),
        opts,
    )

    for i, geom in enumerate(geometries):
        feat = QgsFeature()
        feat.setFields(fields)
        feat.setAttribute("id", i)
        feat.setGeometry(geom)
        writer.addFeature(feat)

    del writer


def _is_name(node, name):
    return isinstance(node, ast.Name) and node.id == name


def _literal(node, env=None):
    if env is None:
        env = {}

    if isinstance(node, ast.Name):
        if node.id in env:
            return env[node.id]
        raise ValueError(f"Unknown symbol: {node.id}")

    if isinstance(node, ast.Constant):
        return node.value

    if isinstance(node, ast.List):
        return [_literal(elt, env) for elt in node.elts]

    if isinstance(node, ast.Tuple):
        return tuple(_literal(elt, env) for elt in node.elts)

    if isinstance(node, ast.Dict):
        return {
            _literal(k, env): _literal(v, env) for (k, v) in zip(node.keys, node.values)
        }

    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        return -_literal(node.operand, env)

    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
        if node.func.id == "list" and len(node.args) == 1:
            return list(_literal(node.args[0], env))
        if node.func.id == "tuple" and len(node.args) == 1:
            return tuple(_literal(node.args[0], env))

    return ast.literal_eval(node)


def _parse_geom_call(node, env):
    if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Name):
        return None

    if node.func.id == "create_line" and node.args:
        return {"type": "line", "coords": _literal(node.args[0], env)}

    if node.func.id == "create_polygon" and len(node.args) >= 2:
        return {
            "type": "polygon",
            "outer": _literal(node.args[0], env),
            "inners": _literal(node.args[1], env),
        }

    if node.func.id == "create_point" and node.args:
        return {"type": "point", "coord": _literal(node.args[0], env)}

    return None


def _extract_build_call(method_body):
    for stmt in method_body:
        call = None
        if isinstance(stmt, ast.Assign) and isinstance(stmt.value, ast.Call):
            call = stmt.value
        elif isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Call):
            call = stmt.value

        if (
            call
            and isinstance(call.func, ast.Name)
            and call.func.id == "build_and_launch"
        ):
            return call

    return None


def extract_cases_from_unittest(unittest_path):
    with open(unittest_path, "r", encoding="utf-8") as f:
        src = f.read()

    module = ast.parse(src)

    test_class = None
    for node in module.body:
        if isinstance(node, ast.ClassDef) and node.name == "Test":
            test_class = node
            break

    if test_class is None:
        raise RuntimeError("Class Test not found in reduce_bend_unittest.py")

    cases = []
    next_id = 1

    for fn in test_class.body:
        if not isinstance(fn, ast.FunctionDef):
            continue
        if not fn.name.startswith("test_case"):
            continue

        title = fn.name
        geom_vars = {}
        value_env = {}

        for stmt in fn.body:
            if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1:
                t = stmt.targets[0]
                if isinstance(t, ast.Name):
                    if t.id == "title" and isinstance(stmt.value, ast.Constant):
                        title = str(stmt.value.value)
                        value_env[t.id] = title
                    try:
                        value_env[t.id] = _literal(stmt.value, value_env)
                    except Exception:
                        pass

                    try:
                        geom_spec = _parse_geom_call(stmt.value, value_env)
                    except Exception:
                        geom_spec = None
                    if geom_spec is not None:
                        geom_vars[t.id] = geom_spec

        call = _extract_build_call(fn.body)
        if call is None or len(call.args) < 3:
            print(f"Skipping {fn.name}: no parseable build_and_launch call")
            continue

        # Arg2 should be a list of geometry variables (or a symbol resolving to that list)
        input_specs = []
        input_arg = call.args[1]
        if isinstance(input_arg, ast.Name) and input_arg.id in value_env:
            value = value_env[input_arg.id]
            if isinstance(value, list):
                # cannot reliably map object instances back to geometry specs; keep unsupported
                print(f"Skipping {fn.name}: input list is runtime object list symbol")
                continue

        if isinstance(input_arg, ast.List):
            parse_ok = True
            for elt in input_arg.elts:
                if isinstance(elt, ast.Name) and elt.id in geom_vars:
                    input_specs.append(geom_vars[elt.id])
                else:
                    parse_ok = False
                    break
            if not parse_ok:
                print(f"Skipping {fn.name}: unsupported input list shape")
                continue
        else:
            print(f"Skipping {fn.name}: build_and_launch input is not a list")
            continue

        diameter = _literal(call.args[2], value_env)
        smooth_line = False
        del_outer = False
        del_inner = False

        # positional optional args: del_pol, del_hole, smooth_line
        if len(call.args) >= 4:
            del_outer = bool(_literal(call.args[3], value_env))
        if len(call.args) >= 5:
            del_inner = bool(_literal(call.args[4], value_env))
        if len(call.args) >= 6:
            smooth_line = bool(_literal(call.args[5], value_env))

        for kw in call.keywords:
            if kw.arg == "smooth_line":
                smooth_line = bool(_literal(kw.value, value_env))
            elif kw.arg == "del_pol":
                del_outer = bool(_literal(kw.value, value_env))
            elif kw.arg == "del_hole":
                del_inner = bool(_literal(kw.value, value_env))

        cases.append(
            {
                "id": next_id,
                "source_test": fn.name,
                "title": title,
                "diameter": float(diameter),
                "smooth_line": smooth_line,
                "del_outer": del_outer,
                "del_inner": del_inner,
                "inputs": input_specs,
            }
        )
        next_id += 1

    return cases


def main():
    QgsApplication.setPrefixPath(QGIS_PREFIX_PATH, True)
    app = QgsApplication([], False)
    app.initQgis()

    rust_dir = os.path.dirname(__file__)
    data_dir = os.path.join(rust_dir, "tests", "bend")
    os.makedirs(data_dir, exist_ok=True)

    unittest_path = os.path.join(rust_dir, "..", "tests", "reduce_bend_unittest.py")
    test_cases = extract_cases_from_unittest(unittest_path)

    manifest = []

    for tc in test_cases:
        tid = tc["id"]
        print(f"Generating RB test {tid:02d}: {tc['title']}")

        input_geoms = [build_geom(spec) for spec in tc["inputs"]]
        input_path = os.path.join(data_dir, f"test_rb_{tid:02d}_input.gpkg")
        expected_path = os.path.join(data_dir, f"test_rb_{tid:02d}_expected.gpkg")

        write_gpkg(input_path, input_geoms)

        if input_geoms:
            output_geoms = run_reduce_bend(
                input_geoms,
                tc["diameter"],
                tc["smooth_line"],
                tc["del_outer"],
                tc["del_inner"],
            )
        else:
            output_geoms = []

        write_gpkg(expected_path, output_geoms)

        manifest.append(
            {
                "id": tid,
                "source_test": tc["source_test"],
                "title": tc["title"],
                "diameter": tc["diameter"],
                "smooth_line": tc["smooth_line"],
                "del_outer": tc["del_outer"],
                "del_inner": tc["del_inner"],
                "input_file": f"test_rb_{tid:02d}_input.gpkg",
                "expected_file": f"test_rb_{tid:02d}_expected.gpkg",
                "num_input_features": len(input_geoms),
                "num_output_features": len(output_geoms),
            }
        )

    manifest_path = os.path.join(data_dir, "test_manifest_reduce_bend.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print(f"\nGenerated {len(test_cases)} reduce-bend test cases in {data_dir}")
    print(f"Manifest: {manifest_path}")

    app.exitQgis()


if __name__ == "__main__":
    main()
